spring:
  application:
    name: microservice2
  zipkin:
    enabled: true

server:
  port: 8082
  eureka:
    instance:
      hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

##ZIPKIN
zipkin:
  enabled: true
  service.name: microservice2
  sender.type: web
  base-url: http://localhost:9411/zipkin/

sleuth:
  sampler:
    probability: 1.0

logging:
  level:
    root: info