server:
  port: 8080

eureka:
  instance:
    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: microservice1
          uri: http://localhost:8081
          predicates:
            - Path=/first/**
        - id: microservice2
          uri: http://localhost:8082
          predicates:
            - Path=/second/**
  main:
    web-application-type: reactive

##ZIPKIN

zipkin:
  enabled: true
  service.name: api-gateway
  sender.type: web
  base-url: http://localhost:9411/zipkin/

sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    root: info

